DELETE FROM members_hobby
where MEMBERS_ID LIKE 'M%';

DELETE FROM membewrs_login
WHERE MEMBERS_ID LIKE 'M%';

DELETE FROM hobby_code
WHERE HOBBY_CODE_ID LIKE 'H%';

DELETE FROM gender_code
WHERE GENDER_CODE_ID LIKE 'G%';

DELETE FROM address_code
WHERE ADDRESS_CODE_ID LIKE 'A%';

DELETE FROM members
WHERE TELEPHONE LIKE 'M%';